// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAKy3BSV9UH_olozmfMfzsZ5GQMt5Msrg',
    appId: '1:1021075612505:web:c7ecd41b1b739909dbe248',
    messagingSenderId: '1021075612505',
    projectId: 'kigalicityapp',
    authDomain: 'kigalicityapp.firebaseapp.com',
    storageBucket: 'kigalicityapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwbWnZ5O4wV83nK7EI9dNrEeO0bUhZE9I',
    appId: '1:1021075612505:android:63e25c1e80d89dbddbe248',
    messagingSenderId: '1021075612505',
    projectId: 'kigalicityapp',
    storageBucket: 'kigalicityapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-wAxEkplIRPdHRpLbx_AekCgCOj331A8',
    appId: '1:1021075612505:ios:52cca90b95dca614dbe248',
    messagingSenderId: '1021075612505',
    projectId: 'kigalicityapp',
    storageBucket: 'kigalicityapp.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-wAxEkplIRPdHRpLbx_AekCgCOj331A8',
    appId: '1:1021075612505:ios:52cca90b95dca614dbe248',
    messagingSenderId: '1021075612505',
    projectId: 'kigalicityapp',
    storageBucket: 'kigalicityapp.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAKy3BSV9UH_olozmfMfzsZ5GQMt5Msrg',
    appId: '1:1021075612505:web:74ac2dfe5e6676a7dbe248',
    messagingSenderId: '1021075612505',
    projectId: 'kigalicityapp',
    authDomain: 'kigalicityapp.firebaseapp.com',
    storageBucket: 'kigalicityapp.firebasestorage.app',
  );
}
